package com.customai.coordinator;
import android.content.*; import android.os.SystemClock; import java.lang.reflect.*; import java.util.concurrent.atomic.AtomicBoolean;
public final class VoiceSessionCoordinator {
 private static final String PREF="custom_ai_voice_session_v2"; private static final AtomicBoolean STARTED=new AtomicBoolean(false); private static volatile Object lastService=null; private static volatile long activeEpoch=0;
 static SharedPreferences p(Context c){return c.getSharedPreferences(PREF,0);} static long now(){return SystemClock.elapsedRealtime();}
 public static boolean start(Context c){final Context app=c.getApplicationContext(); if(STARTED.compareAndSet(false,true)){SharedPreferences sp=p(app); sp.edit().putBoolean("coordinator_installed",true).putString("coordinator_version","0.2.14").putBoolean("session_active",false).putString("session_state","IDLE").putString("semantic_state","IDLE").putString("audio_owner","NONE").putString("tts_state","NONE").putLong("tts_session_epoch",0).putString("last_reason","COORDINATOR_BOOT").apply(); Thread t=new Thread(()->loop(app),"CustomAI-SessionCoordinator");t.setDaemon(true);t.start();} return true;}
 private static void loop(Context c){while(true){try{tick(c);}catch(Throwable ignored){} try{Thread.sleep(50);}catch(InterruptedException e){return;}}}
 private static Object service(){try{Class<?> k=Class.forName("com.ai.assistance.operit.services.FloatingChatService");return k.getMethod("getInstance").invoke(null);}catch(Throwable t){return null;}}
 private static boolean wake(Object s){try{return Boolean.TRUE.equals(s.getClass().getMethod("isWakeLaunched").invoke(s));}catch(Throwable t){return false;}}
 private static void tick(Context c){SharedPreferences sp=p(c); Object svc=service(); if(svc!=null&&svc!=lastService){lastService=svc;if(wake(svc))open(c,"WAKE_SERVICE_APPEARED");} if(svc==null&&lastService!=null){lastService=null;close(c,"FLOATING_SERVICE_GONE");return;} long req=sp.getLong("session_open_request_id",0),done=sp.getLong("session_open_consumed_id",0); if(!sp.getBoolean("session_active",false)&&req>done){open(c,"SPEECH_SESSION_REQUEST");sp.edit().putLong("session_open_consumed_id",req).apply();}}
 private static synchronized void open(Context c,String why){SharedPreferences sp=p(c);if(sp.getBoolean("session_active",false))return;long epoch=Math.max(sp.getLong("session_epoch",0),activeEpoch)+1;activeEpoch=epoch;sp.edit().putLong("session_epoch",epoch).putBoolean("session_active",true).putString("session_state","SESSION_OPENING").putString("semantic_state","SESSION_OPENING").putString("audio_owner","NONE").putString("tts_state","NONE").putLong("tts_session_epoch",0).putLong("session_opened_at_ms",now()).putString("last_reason",why).apply();}
 private static synchronized void close(Context c,String why){SharedPreferences sp=p(c);if(!sp.getBoolean("session_active",false))return;long e=sp.getLong("session_epoch",0);sp.edit().putBoolean("session_active",false).putString("session_state","IDLE").putString("semantic_state","IDLE").putString("audio_owner","NONE").putString("tts_state","NONE").putLong("tts_session_epoch",0).putLong("session_closed_epoch",e).putLong("session_closed_at_ms",now()).putString("last_reason",why).apply();}
}